---
name: "Nu Tools Setup"
description: "Sets up modular Nushell tools for release workflows"
author: "ck3mp3r"

inputs: {}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v20

    - name: Setup Nushell via Nix
      shell: bash
      run: |
        echo "Installing Nushell via nix..."
        # Always install latest from nixpkgs since version pinning in nix is more complex
        # and would require specific nixpkgs revisions
        nix profile install nixpkgs#nushell

        # Verify installation
        nu --version

    - name: Install Nu Tools Modules
      shell: bash
      run: |
        # Create nushell config and scripts directories
        mkdir -p ~/.config/nushell/scripts/nu-tools
        # Copy all module files into the scripts directory
        cp ${{ github.action_path }}/modules/*.nu ~/.config/nushell/scripts/nu-tools/

    - name: Set Nu Tools Module Path
      shell: bash
      run: |
        # Add the scripts directory to NU_LIB_DIRS for module discovery
        echo "NU_LIB_DIRS=$HOME/.config/nushell/scripts" >> $GITHUB_ENV

    - name: Verify Installation
      shell: nu {0}
      run: |
        print "Verifying Nu Tools installation..."
        use nu-tools *
        print "Nu Tools modules loaded successfully!"

branding:
  icon: "package"
  color: "blue"