<<<<<<< HEAD
---
name: "Nu Tools Setup"
description: "Sets up modular Nushell tools for release workflows"
author: "ck3mp3r"

inputs: {}

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v20

    - name: Setup Nushell via Nix
      shell: bash
      run: |
        echo "Installing Nushell via nix..."
        # Always install latest from nixpkgs since version pinning in nix is more complex
        # and would require specific nixpkgs revisions
        nix profile install nixpkgs#nushell

        # Verify installation
        nu --version

    - name: Install Nu Tools Modules
      shell: bash
      run: |
        # Create nushell config and scripts directories
        mkdir -p ~/.config/nushell/scripts/nu-tools
        # Copy all module files into the scripts directory
        cp ${{ github.action_path }}/modules/*.nu ~/.config/nushell/scripts/nu-tools/

    - name: Verify Installation
      shell: nu {0}
      run: |
        print "Verifying Nu Tools installation..."
        use nu-tools *
        print "Nu Tools modules loaded successfully!"

branding:
  icon: "package"
  color: "blue"

||||||| parent of 60e9ac5 (feat: add nu-tools action with modular nushell release workflow tools)
=======
name: 'Nu Tools Setup'
description: 'Sets up modular Nushell tools for release workflows'
author: 'ck3mp3r'

inputs: {}

runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v20

    - name: Setup Nushell via Nix
      shell: bash
      run: |
        echo "Installing Nushell via nix..."
        # Always install latest from nixpkgs since version pinning in nix is more complex
        # and would require specific nixpkgs revisions
        nix profile install nixpkgs#nushell
        
        # Verify installation
        nu --version

    - name: Install Nu Tools Modules
      shell: bash
      run: |
        # Create nushell lib directory and copy the entire modules directory as nu-tools
        mkdir -p ~/.local/share/nushell
        cp -r ${{ github.action_path }}/modules ~/.local/share/nushell/nu-tools
        
        # Set NU_LIB_DIRS environment variable for current and future steps
        echo "NU_LIB_DIRS=$HOME/.local/share/nushell" >> $GITHUB_ENV

    - name: Verify Installation
      shell: bash
      run: |
        echo "Verifying Nu Tools installation..."
        echo "NU_LIB_DIRS: $NU_LIB_DIRS"
        ls -la ~/.local/share/nushell/nu-tools/
        nu -c 'print "Nushell is working"'
        nu -c 'use nu-tools *; print "Nu Tools modules loaded successfully"'

branding:
  icon: 'package'
  color: 'blue'
>>>>>>> 60e9ac5 (feat: add nu-tools action with modular nushell release workflow tools)
