---
name: "CI Tools Setup"
description: "Sets up Nushell CI tools from nu-mods repository"
author: "ck3mp3r"

inputs:
  nu-mods-ref:
    description: "Git reference (branch/tag/commit) of nu-mods repository to use"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v20

    - name: Setup Nushell and CI module via Nix
      shell: bash
      run: |
        echo "Installing Nushell and CI module via nix..."

        # Install Nushell from nixpkgs
        nix profile add nixpkgs#nushell

        # Install CI module from nu-mods repository
        nix profile add github:ck3mp3r/nu-mods/${{ inputs.nu-mods-ref }}#ci

        # Verify installation
        nu --version

    - name: Create symlink to CI modules
      shell: nu {0}
      run: |
        mkdir $nu.default-config-dir
        let scripts_dir = ($nu.default-config-dir | path join 'scripts')

        # Symlink scripts to nix profile modules
        ln -s ($env.HOME | path join '.nix-profile' 'share' 'nushell' 'modules') $scripts_dir

        print $"✓ Created symlink from ($scripts_dir) to nix profile modules"

    - name: Verify Installation
      shell: nu {0}
      run: |
        print "Verifying CI tools installation..."
        use ci *
        print "CI modules loaded successfully!"

branding:
  icon: "terminal"
  color: "green"
