---
name: "Update Flake Lock Files"
description: "An action to update flake.lock files in a repository."

inputs:
  update-branch:
    description: "Branch name for updates"
    required: false
    default: "update-flake-lock"
  main-branch:
    description: "Branch to base off of."
    required: false
    default: "main"
  github-token:
    description: "GitHub token for authentication"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.main-branch }}
        token: ${{ inputs.github-token || github.token }}

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v17
